Script builder.
apidaze/sdk-dotnet pull request #11
Opened 2020-02-05 10:42 UTC by bednarz1990

2020-02-05 11:12 UTC, barinali requested changes

2020-02-05 11:12 UTC, barinali commented on APIdaze.SDK/Validates/CredentialsValidator.cs
>  namespace APIdaze.SDK.Validates
Please, use the imperative form in class names, folder names, namespaces, methods.

2020-02-05 11:12 UTC, barinali commented on APIdaze.SDK/ScriptsBuilders/POCO/Playback.cs
> +namespace APIdaze.SDK.ScriptsBuilders
I think it should be `ScriptBuilder` instead of `ScriptsBuilders` as it generates only one script. They would require us to update the associated namespace and maybe even related classes, methods, and so on.

2020-02-05 11:12 UTC, barinali commented on APIdaze.SDK/Recordings/Recordings.cs
>              SaveFileToFolder(sourceFileName, target, response);
Let's return the FileInfo of the created file as well for the sake of consistency between this and `DownloadRecordingToFile`.

2020-02-05 11:48 UTC, bednarz1990 commented on APIdaze.SDK/Validates/CredentialsValidator.cs
>  namespace APIdaze.SDK.Validates
Validates is in Java SDK as well.

2020-02-06 12:33 UTC, shadzik requested changes

2020-02-06 12:33 UTC, shadzik commented on Apidaze.SDK/Recordings/Recordings.cs
> +            return SaveFileToFolder(sourceFileName, target, response);
Could we get rid of duplicate code in async vs sync methods? Throughout the whole SDK

2020-02-06 14:33 UTC, merged