Fix for structure folders.
apidaze/sdk-dotnet pull request #12
Opened 2020-02-05 13:17 UTC by bednarz1990

2020-02-05 13:22 UTC, barinali requested changes
Could we also rename `/Apidaze.SDK.Tests.Integration` to `/APIdaze.SDK.Tests.Integration`?

2020-02-05 14:47 UTC, shadzik commented
It's still not consistent, once it's called APIdaze and once Apidaze

2020-02-05 17:46 UTC, shadzik requested changes
As discussed, the name should be Apidaze

2020-02-06 09:15 UTC, barinali approved these changes

2020-02-06 09:31 UTC, shadzik approved these changes

2020-02-06 10:55 UTC, merged