Update Readme.md
apidaze/sdk-dotnet pull request #20
Opened 2020-02-12 15:22 UTC by bednarz1990

2020-02-12 15:57 UTC, barinali requested changes

2020-02-12 15:57 UTC, barinali commented on README.md
> +```
Please, take care of the indentations.

2020-02-12 15:57 UTC, barinali commented on README.md
> +```
Please, take care of the indentations.

2020-02-12 15:57 UTC, barinali commented on README.md
> +```
Please, take care of the indentations.

2020-02-12 15:57 UTC, barinali commented on README.md
> +```
Please, take care of the indentations.

2020-02-12 15:57 UTC, barinali commented on README.md
> +```
Please, take care of the indentations.

2020-02-12 15:57 UTC, barinali commented on README.md
> +```
Please, take care of the indentations.

2020-02-13 09:33 UTC, shadzik approved these changes

2020-02-13 09:33 UTC, shadzik commented on README.md
> +- .NET Core 3.1
This is really the only requirement?

2020-02-13 09:56 UTC, barinali requested changes
I still think the code blocks should not have any indentations for the first level.

It should be as the following
```csharp
var credentials = new Credentials(API_KEY, API_SECRET);
```
instead of 
```csharp
    var credentials = new Credentials(API_KEY, API_SECRET);
```

2020-02-13 09:57 UTC, bednarz1990 commented on README.md
> +- .NET Core 3.1
Only one to start using SDK.

2020-02-13 10:45 UTC, bednarz1990 commented on README.md
> +```
ok

2020-02-13 10:45 UTC, bednarz1990 commented on README.md
> +```
Fixed.

2020-02-13 10:45 UTC, bednarz1990 commented on README.md
> +```
Fixed.

2020-02-13 10:46 UTC, bednarz1990 commented on README.md
> +```
Fixed.

2020-02-13 10:46 UTC, bednarz1990 commented on README.md
> +```
Fixed.

2020-02-13 10:46 UTC, bednarz1990 commented on README.md
> +```
Fixed.

2020-02-13 10:49 UTC, barinali approved these changes

2020-02-13 10:49 UTC, merged