Structure folder fix.
apidaze/sdk-dotnet pull request #22
Opened 2020-02-13 11:15 UTC by bednarz1990

2020-02-13 14:39 UTC, shadzik approved these changes

2020-02-13 15:08 UTC, barinali requested changes

2020-02-13 15:08 UTC, barinali commented on Apidaze.SDK.Tests.Integration/CredentialsValidationExample/CredentialsValidationExample.csproj
> +    <UpgradeBackupLocation>C:\Users\bednarz\Desktop\apidaze\sdk-dotnet\Backup\Apidaze.SDK.Tests.Integration\CredentialsValidationExample\</UpgradeBackupLocation>
Could this value be a relative path?

2020-02-13 17:12 UTC, bednarz1990 commented on Apidaze.SDK.Tests.Integration/CredentialsValidationExample/CredentialsValidationExample.csproj
> +    <UpgradeBackupLocation>C:\Users\bednarz\Desktop\apidaze\sdk-dotnet\Backup\Apidaze.SDK.Tests.Integration\CredentialsValidationExample\</UpgradeBackupLocation>
Fixed.

2020-02-14 09:31 UTC, barinali approved these changes

2020-02-14 09:31 UTC, merged