Sdk 92 - sipusers.
apidaze/sdk-dotnet pull request #25
Opened 2020-02-14 18:30 UTC by bednarz1990

2020-02-14 18:35 UTC, shadzik requested changes

2020-02-14 18:35 UTC, shadzik commented on .gitignore
> +Apidaze.SDK.Tests.Integration/CreateSipUserExample/client-secrets.json
Somethings up here again

2020-02-14 18:35 UTC, shadzik commented on Apidaze.SDK.Tests.Integration/GetSipUsers/Program.cs
> +        /// <param name="args">The arguments.</param>
args are the arguments? No way Sherlock :) But what kind of arguments do you expect? :)

2020-02-14 18:35 UTC, shadzik commented on Apidaze.SDK/ApiActionFactory.cs
> +        internal ApiActionFactory(Credentials credentials, string url = "https://cpaas-api.dev.voipinnovations.com/")
Wrong URL, even if it's sandbox, we strive for production

2020-02-14 18:35 UTC, shadzik commented on Apidaze.SDK/ApplicationManager.cs
> +            string url = "https://cpaas-api.dev.voipinnovations.com/")
Same here

2020-02-14 18:35 UTC, shadzik commented on Apidaze.SDK/CdrHttpHandlers/CdrHttpHandlers.cs
> +        ///     Updates the CDR HTTP handler.
Leading white spaces are better?

2020-02-14 18:46 UTC, bednarz1990 commented on Apidaze.SDK/CdrHttpHandlers/CdrHttpHandlers.cs
> +        ///     Updates the CDR HTTP handler.
I think this is better for reading.

2020-02-17 13:16 UTC, shadzik approved these changes

2020-02-17 14:02 UTC, barinali approved these changes

2020-02-17 15:49 UTC, merged